name: Publish site using gatsby

on:
  push:
    branches:
      - main

env:
  GATSBY_PATH_PREFIX: /cat-logic
  GATSBY_SITE_URL: https://edunga1.github.io/cat-logic
  GATSBY_CONTENT_PATH: ${{ github.workspace }}/docs/wiki
  GITHUB_REPOSITORY_URL: https://github.com/edunga1/cat-logic
  GATSBY_GOOGLE_ANALYTICS_TRACKING_ID: ${{ vars.GATSBY_GOOGLE_ANALYTICS_TRACKING_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout cat-logic-site repository
        uses: actions/checkout@v3
        with:
          repository: Edunga1/cat-logic-site
          path: cat-logic-site
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: ./cat-logic-site
      - name: Build
        run: npm run build
        working-directory: ./cat-logic-site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cat-logic-site/public
